compliance:
  - GDPR
  - WCAG 2.1

data_sensitivity: public

project_type: wordpress

development_status: active

license: gpl-3.0

audience:
  - developers
  - wordpress-users
  - e-commerce-businesses

tech_stack:
  - PHP
  - WordPress Block Editor
  - WooCommerce

version: 1.4.1

documentation_url: https://lsx.design/docs/

support_url: https://support.lightspeedwp.agency/

project_priority: core
