version: 2.1
orbs:
  php: circleci/php@1
  evals: circleci/evals@1.0
jobs:
  test-php:
    docker:
      - image: cimg/php:8.2.7-node
    steps:
      - checkout
      - php/install-packages
      - run:
          name: run tests
          command: ./vendor/bin/phpunit
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
      - run:
          name: found github actions config
          command: ":"
  eval-default-node-npm:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            
            npm install
      - evals/eval:
          circle_pipeline_id: << pipeline.id >>
          cmd: npm run evals
workflows:
  build-and-test:
    jobs:
      - test-php:
          context:
            - OpenAI-circleci-lightspeedwp
  evals:
    jobs:
      - eval-default-node-npm:
          context:
            - OpenAI-circleci-lightspeedwp
